/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    users: User;
    projects: Project;
    locations: Location;
    pointsOfInterests: PointsOfInterest;
    'timeline-items': TimelineItem;
    'poi-categories': PoiCategory;
    mapPoints: MapPoint;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    pointsOfInterests: PointsOfInterestsSelect<false> | PointsOfInterestsSelect<true>;
    'timeline-items': TimelineItemsSelect<false> | TimelineItemsSelect<true>;
    'poi-categories': PoiCategoriesSelect<false> | PoiCategoriesSelect<true>;
    mapPoints: MapPointsSelect<false> | MapPointsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('cs' | 'en') | ('cs' | 'en')[];
  globals: {};
  globalsSelect: {};
  locale: 'cs' | 'en';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * External source mapping (e.g. Realpad resource UID)
   */
  external?: {
    realpad?: {
      /**
       * Realpad immutable resource UID
       */
      uid?: string | null;
      type?: ('pdf' | 'plan' | 'image' | 'other') | null;
    };
  };
  prefix?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'viewer' | 'editor' | 'superadmin';
  fullName?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Manage real estate development projects
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * Main project name displayed to users
   */
  title: string;
  slug: string;
  /**
   * Optional tagline or secondary title
   */
  subtitle?: string | null;
  /**
   * City where the project is located
   */
  city?: string | null;
  /**
   * Current phase of the project
   */
  status: 'planned' | 'current' | 'finished';
  /**
   * Optional project logo (stored in Media).
   */
  logo?: (number | null) | Media;
  /**
   * Choose whether the project hero is an image, an uploaded video, or a YouTube video.
   */
  heroType: 'image' | 'video' | 'youtube';
  /**
   * Main project image for listings and headers
   */
  cover?: (number | null) | Media;
  /**
   * Upload a video file to use as the hero media.
   */
  heroVideo?: (number | null) | Media;
  /**
   * Paste a full YouTube URL (watch or youtu.be).
   */
  heroYouTubeUrl?: string | null;
  /**
   * Select which content sections to display for this project. New tabs will appear for each selected section.
   */
  sections?: ('location' | 'gallery' | 'standards' | 'timeline' | 'units' | 'model3d' | 'amenities')[] | null;
  /**
   * Settings for project presentation on the dashboard view
   */
  dashboard?: {
    /**
     * Latitude coordinate for map pin (e.g., 50.0875)
     */
    pinLat?: number | null;
    /**
     * Longitude coordinate for map pin (e.g., 14.4213)
     */
    pinLng?: number | null;
    /**
     * Short label shown on project badge (e.g., "New", "Bestseller")
     */
    badgeLabel?: string | null;
  };
  locationTab?: {
    /**
     * Select location configuration with map data and nearby POIs
     */
    location?: (number | null) | Location;
  };
  galleryTab?: {
    /**
     * Upload/select images for the project gallery (stored in Media).
     */
    gallery?: (number | Media)[] | null;
  };
  standardsTab?: {
    /**
     * Upload PDF brochures, floor plans, and specification documents
     */
    standards?: (number | Media)[] | null;
  };
  timelineTab?: {
    /**
     * Select timeline items for this project (items are stored in Timeline Items collection).
     */
    timelineItems?: (number | TimelineItem)[] | null;
  };
  unitsTab?: {
    /**
     * Configure automatic sync with Realpad pricelist. Credentials are stored securely and never exposed to frontend.
     */
    realpad?: {
      /**
       * Turn on automatic synchronization with Realpad
       */
      enabled?: boolean | null;
      baseUrl?: string | null;
      /**
       * Realpad account username
       */
      login?: string | null;
      /**
       * Realpad account password (never exposed to frontend)
       */
      password?: string | null;
      /**
       * Realpad screen identifier
       */
      screenId?: number | null;
      /**
       * Realpad project identifier
       */
      projectId?: string | null;
      /**
       * Realpad developer identifier
       */
      developerId?: number | null;
      /**
       * How often to sync data from Realpad (in minutes). Default: 60
       */
      syncFrequencyMinutes?: number | null;
      /**
       * When the last sync occurred
       */
      lastSyncAt?: string | null;
      /**
       * Status of the last sync attempt
       */
      lastSyncStatus?: ('ok' | 'error' | 'skipped') | null;
      /**
       * Error message if the last sync failed
       */
      lastSyncError?: string | null;
    };
  };
  model3dTab?: {
    /**
     * 3D visualization file (e.g., Unity WebGL build, glTF model)
     */
    model3d?: (number | null) | Media;
  };
  amenitiesTab?: {
    /**
     * List amenities/features shown on the project detail.
     */
    amenities?:
      | {
          title: string;
          icon?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  centerLat: number;
  centerLng: number;
  defaultZoom?: number | null;
  filters?:
    | {
        key: string;
        label: string;
        icon?: (number | null) | Media;
        defaultOn?: boolean | null;
        id?: string | null;
      }[]
    | null;
  pointsOfInterests?: (number | PointsOfInterest)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pointsOfInterests".
 */
export interface PointsOfInterest {
  id: number;
  name: string;
  category: number | PoiCategory;
  lat: number;
  lng: number;
  distanceText?: string | null;
  description?: string | null;
  logo?: (number | null) | Media;
  links?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "poi-categories".
 */
export interface PoiCategory {
  id: number;
  /**
   * Technický klíč (např. school, shop, park)
   */
  key: string;
  name: string;
  /**
   * Ikona kategorie (volitelné)
   */
  icon?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline-items".
 */
export interface TimelineItem {
  id: number;
  project: number | Project;
  preset: 'custom' | 'item1' | 'item2';
  title: string;
  description?: string | null;
  from: string;
  to?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mapPoints".
 */
export interface MapPoint {
  id: number;
  /**
   * Ke kterému projektu bod patří
   */
  project: number | Project;
  name: string;
  /**
   * Zeměpisná šířka
   */
  lat: number;
  /**
   * Zeměpisná délka
   */
  lng: number;
  /**
   * 3D model, který se otevře po kliknutí
   */
  model3d?: string | null;
  /**
   * Náhled do popupu (bez načítání 3D)
   */
  poster?: (number | null) | Media;
  /**
   * Volitelné řazení bodů
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'pointsOfInterests';
        value: number | PointsOfInterest;
      } | null)
    | ({
        relationTo: 'timeline-items';
        value: number | TimelineItem;
      } | null)
    | ({
        relationTo: 'poi-categories';
        value: number | PoiCategory;
      } | null)
    | ({
        relationTo: 'mapPoints';
        value: number | MapPoint;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  external?:
    | T
    | {
        realpad?:
          | T
          | {
              uid?: T;
              type?: T;
            };
      };
  prefix?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  fullName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  city?: T;
  status?: T;
  logo?: T;
  heroType?: T;
  cover?: T;
  heroVideo?: T;
  heroYouTubeUrl?: T;
  sections?: T;
  dashboard?:
    | T
    | {
        pinLat?: T;
        pinLng?: T;
        badgeLabel?: T;
      };
  locationTab?:
    | T
    | {
        location?: T;
      };
  galleryTab?:
    | T
    | {
        gallery?: T;
      };
  standardsTab?:
    | T
    | {
        standards?: T;
      };
  timelineTab?:
    | T
    | {
        timelineItems?: T;
      };
  unitsTab?:
    | T
    | {
        realpad?:
          | T
          | {
              enabled?: T;
              baseUrl?: T;
              login?: T;
              password?: T;
              screenId?: T;
              projectId?: T;
              developerId?: T;
              syncFrequencyMinutes?: T;
              lastSyncAt?: T;
              lastSyncStatus?: T;
              lastSyncError?: T;
            };
      };
  model3dTab?:
    | T
    | {
        model3d?: T;
      };
  amenitiesTab?:
    | T
    | {
        amenities?:
          | T
          | {
              title?: T;
              icon?: T;
              description?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  centerLat?: T;
  centerLng?: T;
  defaultZoom?: T;
  filters?:
    | T
    | {
        key?: T;
        label?: T;
        icon?: T;
        defaultOn?: T;
        id?: T;
      };
  pointsOfInterests?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pointsOfInterests_select".
 */
export interface PointsOfInterestsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  lat?: T;
  lng?: T;
  distanceText?: T;
  description?: T;
  logo?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline-items_select".
 */
export interface TimelineItemsSelect<T extends boolean = true> {
  project?: T;
  preset?: T;
  title?: T;
  description?: T;
  from?: T;
  to?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "poi-categories_select".
 */
export interface PoiCategoriesSelect<T extends boolean = true> {
  key?: T;
  name?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mapPoints_select".
 */
export interface MapPointsSelect<T extends boolean = true> {
  project?: T;
  name?: T;
  lat?: T;
  lng?: T;
  model3d?: T;
  poster?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}